#!/bin/bash

#set environment variables for Go
export GOROOT=/usr/src/go
export GOBIN=/gobin
export GOPATH=/go

# Set configuration BPulse properties
sed -i "s/^RESTFUL_SEND_CHANNEL_ADAPTER_HOST.*/RESTFUL_SEND_CHANNEL_ADAPTER_HOST=$BPULSE_HOST/g" $GO_COMMON_LIB_CONFIGURATION_FILE
sed -i "s/^RESTFUL_SEND_CHANNEL_ADAPTER_URL_PORT.*/RESTFUL_SEND_CHANNEL_ADAPTER_URL_PORT=$BPULSE_PORT/g" $GO_COMMON_LIB_CONFIGURATION_FILE
sed -i "s/^RESTFUL_SEND_CHANNEL_ADAPTER_URL_PWD.*/RESTFUL_SEND_CHANNEL_ADAPTER_URL_PWD=$BPULSE_PWD/g" $GO_COMMON_LIB_CONFIGURATION_FILE
sed -i "s/^RESTFUL_SEND_CHANNEL_ADAPTER_USER.*/RESTFUL_SEND_CHANNEL_ADAPTER_USER=$BPULSE_USER/g" $GO_COMMON_LIB_CONFIGURATION_FILE

# run
cd $GOBIN
pwd
ls -la
./example -bpulseid $BPULSEID




